### ISSUE TITLE
Pulling evar data limited to 10 observations

### ISSUE THREAD

**Issue by zark-stark12** [dancingcactus/python-omniture#104]
So I've been using this API and is has worked and pulled data correctly for me for some time. However pulling specific evars from a report I do run into issues where it seems the results of the report are limited to only the first 10 observations.

The report being pulled is simple but as an example just pulling the current day, it pulls the data correctly comparing it back to the Omniture data but it is only limited to 10 rows.

Sample code:

`report = suite.report \
                .element('evarXX') \
                .metric('eventXXX') \
                .run(defaultheartbeat=False)`

Is this behavior suppose to happen when working with evars? Any help would be appreciated!

**Comment by dancingcactus** [comment]
This is the default for evars. if you add `top` to the element command it will return the number of rows specified. I think the limit is 50k. In which case you can add a `startingWith` to do pagination. 

```Python
report = suite.report \ 
     .element('evarXX', top=x) \ 
     .metric('eventXXX') \ 
     .run(defaultheartbeat=False)
```
