### ISSUE TITLE
Can't install package - README.md missing

### ISSUE THREAD

**Issue by docgoodtimes** [dancingcactus/python-omniture#55]
Hi! I'm trying to install the package through pip and I'm getting the following error:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\bontempl\appdata\local\temp\pip-build-bgzlyn\omniture\setup
.py", line 5, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'

Could you guys help out please?

Thanks!

**Comment by docgoodtimes** [comment]
Solved with local install commenting out setup(long_description), would be nice to have it fixed anyway :)

**Comment by dancingcactus** [comment]
Agreed. I will take a look and get it fixed.

**Comment by ksayee** [comment]
pip install omniture

File "<string>", line 1, in <module>
      File "/private/var/folders/8m/pbls7h5j7zqfzsbf9kvmxh_12ksfg4/T/pip-build-qiemfy08/omniture/setup.py", line 5, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8m/pbls7h5j7zqfzsbf9kvmxh_12ksfg4/T/pip-build-qiemfy08/omniture/

I'm getting this error, can someone please help?
