### ISSUE TITLE
How to set the library to request Overtime report or ranked report?

### ISSUE THREAD

**Issue by turing4ever** [dancingcactus/python-omniture#66]
Hi there, 

I am running into issues when pulling Average Time Spent on Site metric. The error message:

> InvalidReportError: metric_unsupported_in_trended: Metric "averagetimespentonsite" not supported in trended reports

However, I don't see any option when running a report to set the report type to ranked or overtime. Is there any way to do that?

**Comment by dancingcactus** [comment]
@turing4ever the report type is actually determined by the the parameters you hand it. The table about half way down on this page is a helpful reference. https://marketing.adobe.com/developer/documentation/analytics-reporting-1-4/get-started
